version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=book-store
      - DB_PORT=5432

  db:
    image: "postgres:14.7-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: book-store
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: